name: ipynb -> py

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.ipynb"
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install colab-convert
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: colab-convert ipynb -> py
        run: |
          colab-convert ./Disco_Diffusion.ipynb ./disco.py
      - name: Show diff
        run: |
          git diff ./disco.py
      - name: Commit changes
        run: |
          git config --global pull.rebase false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]@users.name"
          git add disco.py
          git commit -m "Update disco.py" || echo "No changes to commit"
          git pull && git push origin
